<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Email_customer_email</name>
   <tag></tag>
   <elementGuidId>11b7fbe5-c12e-4708-8ca7-d6b0551c5cf9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//input[@name='customer_email'])[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.username > input[name=&quot;customer_email&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0f51e5d2-91ed-46b4-b181-423f61ada795</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>4c9687d9-6c26-4b25-b460-51bfadf0307c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Alamat Email</value>
      <webElementGuid>b0d8e37a-052d-4046-82d2-56cb6408fa26</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>customer_email</value>
      <webElementGuid>dca48862-4649-4e71-a53f-0cc66a8e09e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[@class=&quot;berrybenka&quot;]/div[@class=&quot;wrapper&quot;]/form[@class=&quot;form-horizontal&quot;]/div[@class=&quot;login-inside&quot;]/div[@class=&quot;login&quot;]/div[@class=&quot;username&quot;]/input[1]</value>
      <webElementGuid>28630f58-92dc-44de-b1ba-beda18b83da2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@name='customer_email'])[2]</value>
      <webElementGuid>5faa17bc-b1a6-441b-913d-1e1b0410d491</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/input</value>
      <webElementGuid>97dcd4d2-6b71-4a20-a664-45c7c68fe3ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @placeholder = 'Alamat Email' and @name = 'customer_email']</value>
      <webElementGuid>0417e9dd-f59d-49db-af1c-0a7ff048810c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
