<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Start now</name>
   <tag></tag>
   <elementGuidId>6bf7d64d-77ca-42a2-bbbf-7291fb9e660c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.btn_start_now</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='hs_cos_wrapper_module_71541679625']/div/div/div[4]/div/div[3]/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>59ec20df-1b2f-4bba-8c0b-3c2e809763ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn_start_now</value>
      <webElementGuid>66a74d4b-71b4-49c0-b2ec-b2aa30c26f08</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Start now</value>
      <webElementGuid>3790955f-2bd9-4eda-8390-78acd34ec316</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;hs_cos_wrapper_module_71541679625&quot;)/div[@class=&quot;survey-job&quot;]/div[@class=&quot;survey_container container-fluid&quot;]/div[@class=&quot;survey_tab bundle_show free active&quot;]/div[@class=&quot;left_content&quot;]/div[@class=&quot;bunder_show_button&quot;]/div[@class=&quot;btn_start_now&quot;]</value>
      <webElementGuid>5f0a0196-a8e7-46eb-a0f7-7e1c436318bb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='hs_cos_wrapper_module_71541679625']/div/div/div[4]/div/div[3]/div</value>
      <webElementGuid>3e46556e-3d70-4a66-a822-f28d99a6210c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Know exactly why your web is not working correctly through test reports and analytics.'])[1]/following::div[2]</value>
      <webElementGuid>72283bc9-ed08-4856-a35a-a72e18c17331</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Actionable insights to fix failures ASAP'])[1]/following::div[3]</value>
      <webElementGuid>8b7680f0-bf8c-4631-9fd5-4cc0c8288980</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Go back'])[1]/preceding::div[1]</value>
      <webElementGuid>2a1b6ef1-1c73-403d-9606-97a1a5d29a96</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Start now']/parent::*</value>
      <webElementGuid>3ca41654-80b5-4c46-807c-17825cd2fe87</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div[3]/div</value>
      <webElementGuid>004f3e04-1e8c-4ba7-97df-e89d95bd7926</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Start now' or . = 'Start now')]</value>
      <webElementGuid>26f44fcd-ad30-4c77-9847-64de8558f977</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
