<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_KelurahanKecamatanKode pos wilayahmu</name>
   <tag></tag>
   <elementGuidId>36c477bb-5502-4298-b557-af756a567954</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#select2-x8x2-container</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='select2-x8x2-container']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>0de5ba82-4d71-4009-89e0-0b24a0dd598f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select2-selection__rendered</value>
      <webElementGuid>68681659-c0a5-4792-97c9-8704656094aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>select2-x8x2-container</value>
      <webElementGuid>84802e2f-b320-472a-b16b-d727417ecf4d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>textbox</value>
      <webElementGuid>36d2ba52-04db-41ce-a2cc-d996ead6d531</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-readonly</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>ecb7094d-9005-4dad-a3d1-ea819dab6713</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Kelurahan/Kecamatan/Kode pos wilayahmu</value>
      <webElementGuid>c1dae634-ddc6-492f-ae90-15035bcaa92b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;select2-x8x2-container&quot;)</value>
      <webElementGuid>eac8b174-220e-47db-b82a-ccf789514d51</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='select2-x8x2-container']</value>
      <webElementGuid>b6d210ef-680e-4c33-9f15-196ca9dbcca0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='KELURAHAN/KECAMATAN/KODE POS'])[1]/following::span[4]</value>
      <webElementGuid>09775e8c-3ff2-4f53-9693-8904c90468e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pilih Lokasi Pengiriman'])[1]/following::span[4]</value>
      <webElementGuid>d9f177cd-0636-4b25-a242-454e8d0e4919</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pilih layanan pengiriman'])[1]/preceding::span[5]</value>
      <webElementGuid>5c404325-dfc3-4965-b12d-51e394c28930</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/span/span/span</value>
      <webElementGuid>ff354171-23a8-41ca-9f20-d65cf60ba524</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'select2-x8x2-container' and (text() = 'Kelurahan/Kecamatan/Kode pos wilayahmu' or . = 'Kelurahan/Kecamatan/Kode pos wilayahmu')]</value>
      <webElementGuid>3902eac1-4d3d-436b-b025-69bb8ea55ac9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
